[book]
authors = ["Julian Stecklina", "Zhaofeng Li"]
language = "en"
src = "src"
title = "Celler"

[output.html]
git-repository-url = "https://github.com/blitz/celler"
edit-url-template = "https://github.com/blitz/celler/edit/main/book/{path}"
